version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "java-test-samples"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lolf8bz4v55j"
s3_prefix = "java-test-samples"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
